version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    networks:
      - microservices-network

  register-server:
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    depends_on:
      - mysql
    networks:
      - microservices-network

  gateway-service:
    build:
      context: ./ApiGateway
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - register-server
    networks:
      - microservices-network

  task-service:
    build:
      context: ./TaskService
    ports:
      - "8088:8088"
    depends_on:
      - mysql
      - register-server
      - gateway-service
    networks:
      - microservices-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/taskmanagerservice?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

  user-service:
    build:
      context: ./UserSerivce
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - register-server
      - gateway-service
    networks:
      - microservices-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/usermanagerservice?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8084:80"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge